### ISSUE TITLE
Help ...

### ISSUE THREAD

**Issue by vincent-caron** [Steffens-Bridgemate/WeTransfer-C-wrapper#1]
I'm trying to integrate your dev into mine.

You have a Token property that is set to blank in properties.settings when you watch it in dev, but at runtime it's populate with the correct value .

How and When this value is retrieved .. I can't figure out the way you do that.

Thanks

**Comment by Steffens-Bridgemate** [comment]
Hello Vincent,

Obtaining the Token is done in the Communicator.GetToken function.
