### ISSUE TITLE
Deadlock in Windows Forms

### ISSUE THREAD

**Issue by TIS-Stefan** [Steffens-Bridgemate/WeTransfer-C-wrapper#4]
Hello

I tried your V1 API with the console and it works excellent. Then I implemented that in a Windows Forms application (for drag&drop and creating nice output texts to be sent) but I get a dead lock in         `private async Task<TResponse> WaitForResponse<TResponse>(HttpClient client,HttpRequestMessage request) where TResponse: JsonResponse
`
at the line 
`var response = await client.SendAsync(request);`
called from GetToken()

I am not that experienced in Multi Threading, therefore, I am totally helpless. 

My upload call is:
```
private String Upload(String[] FileNames)
{
	String DownloadURL = "unknown";

	IEnumerable<string> fullPaths = FileNames;

	var uploader = new Communicator(apiKey: "***",
						chunkDirectory: @"b:\"); // ToDo

	var progress = new Progress<ProgressReport>();
	progress.ProgressChanged += (sender, report) => Console.WriteLine($"{report.Message}: {report.Percentage}");
	
	pbUpload.Value = 0;
	
	var result = uploader.UploadFiles(fullPaths,
							 "My downloads",
							 progress).Result;

	DownloadURL = result.DownloadUrl;
	this.Cursor = Cursors.WaitCursor;
	lblFileUpload.Text = "done";
	this.Cursor = Cursors.Arrow;
	return DownloadURL;
}
```
as funtion of Form1.

What do I miss?

Thank you in advance
Stefan

**Comment by Steffens-Bridgemate** [comment]
Hello Stefan,
I have no time now to create a test set-up, but from the top of my head:
Using the .Result property deadlocks when used in a WPF application, so probably as well in a WinForms application.
Proper use is: 
`var result =await uploader.UploadFiles(fullPaths,
							     "My downloads",
							    progress);`

This will cause the compiler to complain that the method header should be:
`private async  Task<String> UploadAsync(String[] FileNames)
`

I am afraid you are about to get further experience with multi-threading and especially the most current implementation of it that uses the async/await pattern.

**Comment by TIS-Stefan** [comment]
Hi

I found a workaround. I simply call the console.exe with a list of files to be uploaded and get the link back. That works absolutely fine.

> I am afraid you are about to get further experience with multi-threading and especially the most current implementation of it that uses the async/await pattern.

You are totally right here :-)

Lets close the case, since I reached by objectives.

Stefan
