### ISSUE TITLE
Unable to get new token using asp.net webform

### ISSUE THREAD

**Issue by mwasif7** [Steffens-Bridgemate/WeTransfer-C-wrapper#5]
Hi Steffens-Bridgemate,
I am trying V2 TRANSFERAPI API to upload the file.
But application got stuck at new token generation.
The application hanged  at the code having
function: WaitForResponse,
code: var response = await client.SendAsync(request);
file: V2\WeTransferCommunicator.cs 
line number: 140.

There is no problem accessing it via console application  but not able to generate token with webform.

Thanks in advance.

**Comment by Steffens-Bridgemate** [comment]
Hello mwasif,

I think you get deadlock by a wrong application of the async await pattern.
In a console application's Main method you use:
var response=GetTokenAsync().Result;

In any other project you need to use:
public async Task DoSomething()
{
   var response=await GetTokenAsync();
}


Can you post the entire call stack that precedes the call to await client.SendAsync(request)?

**Comment by mwasif7** [comment]
Hi Steffen,Thanks alot it solved my problem.I have been not using async and await to parent method.cheers!WasifOn 18-Nov-2019 3:55 PM, Steffens-Bridgemate <notifications@github.com> wrote:Hello mwasif,
I think you get deadlock by a wrong application of the async await pattern.
In a console application's Main method you use:
var response=GetTokenAsync().Result;
In any other project you need to use:
public async Task DoSomething()
{
var response=await GetTokenAsync();
}
Can you post the entire call stack that precedes the call to await client.SendAsync(request)?
